version: '3.8'
services:
  postgres:
    container_name: coderun-pg-dev
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
