version: '3'
services:
  spring-boot-app:
    build: .
    depends_on:
      - docker-client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker-client: # This is the Docker service
    image: docker:dind
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

